project_id = "caawgzuofnujrznwbuxk"

[functions.track-anonymous]
verify_jwt = false

[functions.content-feed]
verify_jwt = false

[functions.fetch-market-data]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true

[functions.sync-portfolio-prices]
verify_jwt = true

[functions.fetch-news]
verify_jwt = false

[functions.public-data]
verify_jwt = false

[functions.update-live-status]
verify_jwt = false

[functions.social-meta-oauth-callback]
verify_jwt = false