project_id = "caawgzuofnujrznwbuxk"

[functions.track-anonymous]
verify_jwt = false

[functions.content-feed]
verify_jwt = false

[functions.fetch-market-data]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true

[functions.sync-portfolio-prices]
verify_jwt = true

[functions.fetch-news]
verify_jwt = false

[functions.public-data]
verify_jwt = false

[functions.update-live-status]
verify_jwt = false

[functions.social-meta-oauth-callback]
verify_jwt = false

[functions.ai-lab-explain]
verify_jwt = false

[functions.fetch-social-news]
enabled = true
verify_jwt = true
import_map = "./functions/fetch-social-news/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/fetch-social-news/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/fetch-social-news/*.html" ]
