-- Automatic emails for explicitly opted-in users; credentials remain in Vault.
begin;
select cron.schedule('news-highlights-weekdays', '15 3 * * 1-5', $job$ select net.http_post(url := rtrim((select decrypted_secret from vault.decrypted_secrets where name='kff_project_url'),'/') || '/functions/v1/run-news-highlights-edition', headers := jsonb_build_object('Content-Type','application/json','apikey',(select decrypted_secret from vault.decrypted_secrets where name='kff_automations_secret_key')), body := '{}'::jsonb, timeout_milliseconds := 120000); $job$);
select cron.schedule('market-overview-weekdays', '0 15 * * 1-5', $job$ select net.http_post(url := rtrim((select decrypted_secret from vault.decrypted_secrets where name='kff_project_url'),'/') || '/functions/v1/generate-market-overview', headers := jsonb_build_object('Content-Type','application/json','apikey',(select decrypted_secret from vault.decrypted_secrets where name='kff_automations_secret_key')), body := '{"use_ai":true,"enforce_after_close":true}'::jsonb, timeout_milliseconds := 120000); $job$);
select cron.schedule('market-brief-weekdays', '15 15 * * 1-5', $job$ select net.http_post(url := rtrim((select decrypted_secret from vault.decrypted_secrets where name='kff_project_url'),'/') || '/functions/v1/enqueue-market-brief', headers := jsonb_build_object('Content-Type','application/json','apikey',(select decrypted_secret from vault.decrypted_secrets where name='kff_automations_secret_key')), body := '{}'::jsonb, timeout_milliseconds := 120000); $job$);
select cron.schedule('process-market-brief', '* * * * *', $job$ select net.http_post(url := rtrim((select decrypted_secret from vault.decrypted_secrets where name='kff_project_url'),'/') || '/functions/v1/process-communication-outbox', headers := jsonb_build_object('Content-Type','application/json','apikey',(select decrypted_secret from vault.decrypted_secrets where name='kff_automations_secret_key')), body := '{"category":"market_brief","batch_size":5}'::jsonb, timeout_milliseconds := 120000); $job$);
select cron.schedule('process-news-highlights', '* * * * *', $job$ select net.http_post(url := rtrim((select decrypted_secret from vault.decrypted_secrets where name='kff_project_url'),'/') || '/functions/v1/process-communication-outbox', headers := jsonb_build_object('Content-Type','application/json','apikey',(select decrypted_secret from vault.decrypted_secrets where name='kff_automations_secret_key')), body := '{"category":"news_highlights","batch_size":5}'::jsonb, timeout_milliseconds := 120000); $job$);
commit;

