// This file is automatically generated / managed.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getValidatedSupabaseConfig } from '@/lib/supabase-config';

const { supabaseUrl, supabasePublishableKey, supabaseProjectId } = getValidatedSupabaseConfig();

export const SUPABASE_PROJECT_ID = supabaseProjectId;

export const supabase = createClient<Database>(supabaseUrl, supabasePublishableKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'implicit',
  },
});
